services:
  totem:
    build: .
    image: totemengine
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

  server:
    image: totemengine
    ports:
      - "8000:8000"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    command: ["server", "--host", "0.0.0.0", "--port", "8000"]
